# Generated by Django 6.0.5 on 2026-06-08 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost_in_coins', models.PositiveIntegerField(verbose_name='Цена в коинах')),
                ('reward_type', models.CharField(choices=[('discount', 'Скидка'), ('product', 'Товар'), ('merch', 'Мерч'), ('other', 'Другое')], max_length=20, verbose_name='Тип вознаграждения')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент скидки (если применимо)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
            },
        ),
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс коинов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек Плюс Коинов',
                'verbose_name_plural': 'Кошельки Плюс Коинов',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма')),
                ('operation', models.CharField(choices=[('earn', 'Начисление'), ('spend', 'Списание')], max_length=5, verbose_name='Тип операции')),
                ('reason', models.TextField(verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.coinwallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Транзакция коинов',
                'verbose_name_plural': 'Транзакции коинов',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма покупок')),
                ('discount_level', models.PositiveSmallIntegerField(default=0, verbose_name='Текущий уровень скидки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дисконтные карты',
            },
        ),
    ]
