# Generated by Django 6.0.5 on 2026-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='discount_level',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Текущий уровень скидки'),
        ),
    ]
