# Generated by Django 6.0.5 on 2026-06-22 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_loyaltycard_discount_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс баллов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installer_points', to=settings.AUTH_USER_MODEL, verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'Баллы монтажника',
                'verbose_name_plural': 'Баллы монтажников',
            },
        ),
    ]
