# Generated by Django 6.0.5 on 2026-06-02 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinstallerrelation',
            name='installer',
            field=models.OneToOneField(limit_choices_to={'role': 'installer'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerinstallerrelation',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='installers', to=settings.AUTH_USER_MODEL),
        ),
    ]
