# Generated by Django 6.0.5 on 2026-06-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('returned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='purchases.purchase', verbose_name='Исходная покупка')),
            ],
            options={
                'verbose_name': 'Возврат покупки',
                'verbose_name_plural': 'Возвраты покупок',
                'ordering': ['-returned_at'],
            },
        ),
    ]
