# Generated by Django 6.0.5 on 2026-06-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchasereturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID (1C)'),
        ),
    ]
