# Generated by Django 6.0.5 on 2026-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Электронный чек'),
        ),
    ]
